// Generated by CoffeeScript 1.6.2
/*
// ==UserScript==
// @id             ajax_pixiv_bookmark
// @name           AJAX Pixiv Bookmark
// @version        2.0.1
// @namespace      http://blog.k2ds.net/
// @author         killtw
// @description    Using AJAX to add a bookmark in Pixiv
// @match          http://www.pixiv.net/member_illust.php?*
// ==/UserScript==
*/

var addjQuery, main;

addjQuery = function(callback) {
  var e;

  e = document.createElement('script');
  e.setAttribute('src', 'http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js');
  e.addEventListener('load', function() {
    var script;

    script = document.createElement('script');
    script.textContent = "(" + callback.toString() + ")();";
    document.body.appendChild(script);
  });
  document.body.appendChild(e);
};

main = function() {
  $('div.bookmark-container a._button').click(function(e) {
    var illust_id, illust_tags, input_tag;

    e.preventDefault();
    illust_tags = [];
    input_tag = [];
    illust_id = $('input[name="illust_id"]').val();
    $.ajax({
      url: 'http://www.pixiv.net/bookmark_tag_all.php',
      type: 'GET',
      dataType: 'html',
      beforeSend: function() {
        var tag, _i, _len, _ref;

        _ref = $('a.text');
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tag = _ref[_i];
          illust_tags.push(tag.text);
        }
        console.log(illust_tags);
      },
      success: function(data) {
        var tag, _i, _len, _ref;

        _ref = $(data).find('a.tag-name');
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tag = _ref[_i];
          if (illust_tags.indexOf(tag.text) !== -1) {
            input_tag.push(tag.text);
          }
        }
        console.log(input_tag.join(' '));
      },
      complete: function() {
        $.ajax({
          url: 'bookmark_add.php',
          data: {
            mode: 'add',
            tt: $('input[name="tt"]').val(),
            id: illust_id,
            tag: input_tag.join(' '),
            type: 'illust',
            form_sid: '',
            restrict: '0'
          },
          dataType: 'html',
          type: 'POST',
          beforeSend: function() {
            $("div.bookmark-container a._button").text('追加中…');
          },
          success: function() {
            $("div.bookmark-container a._button").text('加入成功');
            $('div.bookmark-container').fadeOut('fast').html('<a href="bookmark_add.php?type=illust&illust_id=' + illust_id + '" class="button-on">編輯收藏</a>').fadeIn('fast');
          }
        });
      }
    });
  });
};

addjQuery(main);
